[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "TDS"
authors = [{name = "Nele Wandel", email = "nele.sophie@gmail.com"}]
dynamic = ["version", "description"]